// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVB1rTCGtAExlsWrSbNMO0R5xX155oQ8Q',
    appId: '1:297892598726:web:13f4224cc0510de31258c7',
    messagingSenderId: '297892598726',
    projectId: 'weather-de8ff',
    authDomain: 'weather-de8ff.firebaseapp.com',
    storageBucket: 'weather-de8ff.firebasestorage.app',
    measurementId: 'G-TCMT8P91BE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBntLb68yGcIH4tDyUvmDFampmuqV5rpA0',
    appId: '1:297892598726:android:4aaa3f25841310791258c7',
    messagingSenderId: '297892598726',
    projectId: 'weather-de8ff',
    storageBucket: 'weather-de8ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZjvsHOjs4t6Vshzz75TTKlP_7OLlYMnM',
    appId: '1:297892598726:ios:8dafabcb410ff3d21258c7',
    messagingSenderId: '297892598726',
    projectId: 'weather-de8ff',
    storageBucket: 'weather-de8ff.firebasestorage.app',
    iosBundleId: 'com.example.weather',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZjvsHOjs4t6Vshzz75TTKlP_7OLlYMnM',
    appId: '1:297892598726:ios:8dafabcb410ff3d21258c7',
    messagingSenderId: '297892598726',
    projectId: 'weather-de8ff',
    storageBucket: 'weather-de8ff.firebasestorage.app',
    iosBundleId: 'com.example.weather',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVB1rTCGtAExlsWrSbNMO0R5xX155oQ8Q',
    appId: '1:297892598726:web:9ba23a3f5dba92bc1258c7',
    messagingSenderId: '297892598726',
    projectId: 'weather-de8ff',
    authDomain: 'weather-de8ff.firebaseapp.com',
    storageBucket: 'weather-de8ff.firebasestorage.app',
    measurementId: 'G-5YHDXMYPZF',
  );
}
